---
# Variable configuration.
- include: variables.yml

# Setup/install tasks.
- include: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: initialize.yml
- include: configure.yml

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"

# Configure PostgreSQL.
- import_tasks: users.yml
- import_tasks: databases.yml
- import_tasks: users_props.yml
