---
- name: MongoDB | Download MongoDB GPG key
  ansible.builtin.get_url:
    url: https://www.mongodb.org/static/pgp/server-8.0.asc
    dest: /usr/share/keyrings/mongodb-server-8.0.asc
    mode: "0644"

- name: MongoDB | De-armor GPG key
  ansible.builtin.shell: |
    gpg --dearmor < /usr/share/keyrings/mongodb-server-8.0.asc > /usr/share/keyrings/mongodb-server-8.0.gpg
  args:
    creates: /usr/share/keyrings/mongodb-server-8.0.gpg

- name: MongoDB | Add MongoDB repository
  ansible.builtin.apt_repository:
    filename: mongodb-org-8.0
    repo: "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/8.0 multiverse"
    state: present
    update_cache: true

- name: MongoDB | Install MongoDB
  apt:
    name: mongodb-org
    state: present
    update_cache: true

- name: MongoDB | Ensure service is running and enabled
  service:
    name: mongod
    enabled: true
    state: started
