- name: Generate SSH key
  hosts: host0
  vars_files:
    - vars/default.yml
  vars_prompt:
    - name: "ssh_passphrase"
      prompt: "Enter the passphrase for the SSH key"
  tasks:
    - name: generate SSH key "{{ssh_key_filename}}"
      user:
        name: "{{app_user}}"
        generate_ssh_key: true
        ssh_key_type: rsa
        ssh_key_bits: 4096
        ssh_key_file: .ssh/{{ssh_key_filename}}
        ssh_key_passphrase: "{{ssh_passphrase}}"
        force: false